### ISSUE TITLE
Opacity Not Supported

### ISSUE THREAD

**Issue by allenhartwig** [adrianopaladini/Live-blurView#1]
I'm not sure if this is a limitation of the view itself, but right now, it's not possible to set the opacity of the view. Setting it lower than a value of 1.0 results in 0.0 (eg. opacity of 0.8 results in an invisible view as if the opacity were 0.0).

**Comment by adrianopaladini** [comment]
The problem is not transparency with a view, but the native effect generated in the toolbar, which does not accept transparency. So, if you put any value other than 1, the effect is not applied and you will have a view without the blur effect. 

This is because Apple does not allow the use of private API's to do this properly effect.
